### ISSUE TITLE
Error When Resuming Training from Pre-trained Model

### ISSUE THREAD

**Issue by kiveboxops** [ZhengPeng7/BiRefNet#100]
## Environment
- **Hardware**: AWS `ml.g5.48xlarge` instance
- **Model**: BiRefNet
- **Dataset**: Custom dataset (~500 images)

## Context
I successfully trained a model from scratch using my custom dataset of approximately 500 images. However, due to the limited dataset size, the results were suboptimal. To improve performance, I attempted to resume training from your pre-trained model using my dataset.

## Changes Made
1. **config.py**: 
   - Updated image paths
   - Set batch size to 1 (failing with 2 or 4)
2. **train.sh**: 
   - Added the `--resume` flag to the `multi-gpu` section

## Error Description
When attempting to resume training, I encountered the following error:

```
RuntimeError: Error(s) in loading state_dict for BiRefNet:
    Unexpected key(s) in state_dict: "squeeze_module.0.dec_att.aspp1.bn.weight", ...
```

The error message indicates a mismatch between the state dictionary of the pre-trained model and the current model architecture. It appears that the pre-trained model contains additional keys that are not present in the current model structure.

## Full Error Log
```shell
(pytorch_env) ➜  tmp git:(main) ✗ OMP_NUM_THREADS=8 ./train_test.sh BiRefNet_general 0,1,2,3,4,5,6,7 0 2>&1 | tee  training-logs.txt
Training started at Fri Oct 4 13:22:04 UTC 2024
Multi-GPU mode received...
2024-10-04 13:22:20,242 INFO datasets: load_all=False, compile=True.
2024-10-04 13:22:20,243 INFO datasets: load_all=False, compile=True.
2024-10-04 13:22:20,243 INFO Other hyperparameters:
2024-10-04 13:22:20,243 INFO Other hyperparameters:
2024-10-04 13:22:20,243 INFO Namespace(resume='/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth', epochs=600, trainset='DIS5K', ckpt_dir='ckpt/BiRefNet_general', testsets='NO', dist=True)
2024-10-04 13:22:20,243 INFO Namespace(resume='/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth', epochs=600, trainset='DIS5K', ckpt_dir='ckpt/BiRefNet_general', testsets='NO', dist=True)
batch size: 1batch size:
 1
2024-10-04 13:22:20,246 INFO datasets: load_all=False, compile=True.
2024-10-04 13:22:20,246 INFO Other hyperparameters:
2024-10-04 13:22:20,246 INFO Namespace(resume='/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth', epochs=600, trainset='DIS5K', ckpt_dir='ckpt/BiRefNet_general', testsets='NO', dist=True)
batch size: 1
2024-10-04 13:22:20,248 INFO datasets: load_all=False, compile=True.
2024-10-04 13:22:20,248 INFO Other hyperparameters:
2024-10-04 13:22:20,248 INFO Namespace(resume='/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth', epochs=600, trainset='DIS5K', ckpt_dir='ckpt/BiRefNet_general', testsets='NO', dist=True)
batch size: 1
58 batches of train dataloader DIS-TR have been created.
58 batches of train dataloader DIS-TR have been created.
2024-10-04 13:22:20,249 INFO datasets: load_all=False, compile=True.
2024-10-04 13:22:20,249 INFO Other hyperparameters:
2024-10-04 13:22:20,249 INFO Namespace(resume='/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth', epochs=600, trainset='DIS5K', ckpt_dir='ckpt/BiRefNet_general', testsets='NO', dist=True)
batch size: 1
2024-10-04 13:22:20,251 INFO datasets: load_all=False, compile=True.
2024-10-04 13:22:20,251 INFO datasets: load_all=False, compile=True.
2024-10-04 13:22:20,251 INFO Other hyperparameters:
2024-10-04 13:22:20,251 INFO Other hyperparameters:
2024-10-04 13:22:20,251 INFO Namespace(resume='/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth', epochs=600, trainset='DIS5K', ckpt_dir='ckpt/BiRefNet_general', testsets='NO', dist=True)
2024-10-04 13:22:20,251 INFO Namespace(resume='/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth', epochs=600, trainset='DIS5K', ckpt_dir='ckpt/BiRefNet_general', testsets='NO', dist=True)
batch size:batch size:  11

58 batches of train dataloader DIS-TR have been created.
58 batches of train dataloader DIS-TR have been created.
2024-10-04 13:22:20,253 INFO datasets: load_all=False, compile=True.
2024-10-04 13:22:20,253 INFO Other hyperparameters:
2024-10-04 13:22:20,253 INFO Namespace(resume='/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth', epochs=600, trainset='DIS5K', ckpt_dir='ckpt/BiRefNet_general', testsets='NO', dist=True)
batch size: 1
58 batches of train dataloader DIS-TR have been created.
58 batches of train dataloader DIS-TR have been created.
58 batches of train dataloader DIS-TR have been created.
58 batches of train dataloader DIS-TR have been created.
Found correct weights in the "model" item of loaded state_dict.
Found correct weights in the "model" item of loaded state_dict.
Found correct weights in the "model" item of loaded state_dict.
Found correct weights in the "model" item of loaded state_dict.
Found correct weights in the "model" item of loaded state_dict.
Found correct weights in the "model" item of loaded state_dict.
Found correct weights in the "model" item of loaded state_dict.
Found correct weights in the "model" item of loaded state_dict.
2024-10-04 13:22:22,686 INFO => loading checkpoint '/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth'
2024-10-04 13:22:22,779 INFO => loading checkpoint '/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth'
2024-10-04 13:22:22,807 INFO => loading checkpoint '/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth'
2024-10-04 13:22:22,816 INFO => loading checkpoint '/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth'
2024-10-04 13:22:22,823 INFO => loading checkpoint '/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth'
2024-10-04 13:22:22,841 INFO => loading checkpoint '/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth'
2024-10-04 13:22:22,847 INFO => loading checkpoint '/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth'
2024-10-04 13:22:22,850 INFO => loading checkpoint '/home/sagemaker-user/BiRefNet/tutorials/data/BiRefNet-general-epoch_244.pth'
Traceback (most recent call last):
  File "/home/sagemaker-user/tmp/train.py", line 337, in <module>
    main()
  File "/home/sagemaker-user/tmp/train.py", line 321, in main
    model_opt_lrsch=init_models_optimizers(args.epochs, to_be_distributed)
  File "/home/sagemaker-user/tmp/train.py", line 106, in init_models_optimizers
    model.load_state_dict(state_dict)
  File "/home/sagemaker-user/.conda/envs/pytorch_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BiRefNet:
        Unexpected key(s) in state_dict: "squeeze_module.0.dec_att.aspp1.bn.weight", "squeeze_module.0.dec_att.aspp1.bn.bias", "squeeze_module.0.dec_att.aspp1.bn.running_mean", "squeeze_module.0.dec_att.aspp1.bn.running_var", "squeeze_module.0.dec_att.aspp1.bn.num_batches_tracked", "squeeze_module.0.dec_att.aspp_deforms.0.bn.weight", "squeeze_module.0.dec_att.aspp_deforms.0.bn.bias", "squeeze_module.0.dec_att.aspp_deforms.0.bn.running_mean", "squeeze_module.0.dec_att.aspp_deforms.0.bn.running_var", "squeeze_module.0.dec_att.aspp_deforms.0.bn.num_batches_tracked", "squeeze_module.0.dec_att.aspp_deforms.1.bn.weight", "squeeze_module.0.dec_att.aspp_deforms.1.bn.bias", "squeeze_module.0.dec_att.aspp_deforms.1.bn.running_mean", "squeeze_module.0.dec_att.aspp_deforms.1.bn.running_var", "squeeze_module.0.dec_att.aspp_deforms.1.bn.num_batches_tracked", "squeeze_module.0.dec_att.aspp_deforms.2.bn.weight", "squeeze_module.0.dec_att.aspp_deforms.2.bn.bias", "squeeze_module.0.dec_att.aspp_deforms.2.bn.running_mean", "squeeze_module.0.dec_att.aspp_deforms.2.bn.running_var", "squeeze_module.0.dec_att.aspp_deforms.2.bn.num_batches_tracked", "squeeze_module.0.dec_att.global_avg_pool.2.weight", "squeeze_module.0.dec_att.global_avg_pool.2.bias", "squeeze_module.0.dec_att.global_avg_pool.2.running_mean", "squeeze_module.0.dec_att.global_avg_pool.2.running_var", "squeeze_module.0.dec_att.global_avg_pool.2.num_batches_tracked", "squeeze_module.0.dec_att.bn1.weight", "squeeze_module.0.dec_att.bn1.bias", "squeeze_module.0.dec_att.bn1.running_mean", "squeeze_module.0.dec_att.bn1.running_var", "squeeze_module.0.dec_att.bn1.num_batches_tracked", "squeeze_module.0.bn_in.weight", "squeeze_module.0.bn_in.bias", "squeeze_module.0.bn_in.running_mean", "squeeze_module.0.bn_in.running_var", "squeeze_module.0.bn_in.num_batches_tracked", "squeeze_module.0.bn_out.weight", "squeeze_module.0.bn_out.bias", "squeeze_module.0.bn_out.running_mean", "squeeze_module.0.bn_out.running_var", "squeeze_module.0.bn_out.num_batches_tracked", "decoder.decoder_block4.dec_att.aspp1.bn.weight", "decoder.decoder_block4.dec_att.aspp1.bn.bias", "decoder.decoder_block4.dec_att.aspp1.bn.running_mean", "decoder.decoder_block4.dec_att.aspp1.bn.running_var", "decoder.decoder_block4.dec_att.aspp1.bn.num_batches_tracked", "decoder.decoder_block4.dec_att.aspp_deforms.0.bn.weight", "decoder.decoder_block4.dec_att.aspp_deforms.0.bn.bias", "decoder.decoder_block4.dec_att.aspp_deforms.0.bn.running_mean", "decoder.decoder_block4.dec_att.aspp_deforms.0.bn.running_var", "decoder.decoder_block4.dec_att.aspp_deforms.0.bn.num_batches_tracked", "decoder.decoder_block4.dec_att.aspp_deforms.1.bn.weight", "decoder.decoder_block4.dec_att.aspp_deforms.1.bn.bias", "decoder.decoder_block4.dec_att.aspp_deforms.1.bn.running_mean", "decoder.decoder_block4.dec_att.aspp_deforms.1.bn.running_var", "decoder.decoder_block4.dec_att.aspp_deforms.1.bn.num_batches_tracked", "decoder.decoder_block4.dec_att.aspp_deforms.2.bn.weight", "decoder.decoder_block4.dec_att.aspp_deforms.2.bn.bias", "decoder.decoder_block4.dec_att.aspp_deforms.2.bn.running_mean", "decoder.decoder_block4.dec_att.aspp_deforms.2.bn.running_var", "decoder.decoder_block4.dec_att.aspp_deforms.2.bn.num_batches_tracked", "decoder.decoder_block4.dec_att.global_avg_pool.2.weight", "decoder.decoder_block4.dec_att.global_avg_pool.2.bias", "decoder.decoder_block4.dec_att.global_avg_pool.2.running_mean", "decoder.decoder_block4.dec_att.global_avg_pool.2.running_var", "decoder.decoder_block4.dec_att.global_avg_pool.2.num_batches_tracked", "decoder.decoder_block4.dec_att.bn1.weight", "decoder.decoder_block4.dec_att.bn1.bias", "decoder.decoder_block4.dec_att.bn1.running_mean", "decoder.decoder_block4.dec_att.bn1.running_var", "decoder.decoder_block4.dec_att.bn1.num_batches_tracked", "decoder.decoder_block4.bn_in.weight", "decoder.decoder_block4.bn_in.bias", "decoder.decoder_block4.bn_in.running_mean", "decoder.decoder_block4.bn_in.running_var", "decoder.decoder_block4.bn_in.num_batches_tracked", "decoder.decoder_block4.bn_out.weight", "decoder.decoder_block4.bn_out.bias", "decoder.decoder_block4.bn_out.running_mean", "decoder.decoder_block4.bn_out.running_var", "decoder.decoder_block4.bn_out.num_batches_tracked", "decoder.decoder_block3.dec_att.aspp1.bn.weight", "decoder.decoder_block3.dec_att.aspp1.bn.bias", "decoder.decoder_block3.dec_att.aspp1.bn.running_mean", "decoder.decoder_block3.dec_att.aspp1.bn.running_var", "decoder.decoder_block3.dec_att.aspp1.bn.num_batches_tracked", "decoder.decoder_block3.dec_att.aspp_deforms.0.bn.weight", "decoder.decoder_block3.dec_att.aspp_deforms.0.bn.bias", "decoder.decoder_block3.dec_att.aspp_deforms.0.bn.running_mean", "decoder.decoder_block3.dec_att.aspp_deforms.0.bn.running_var", "decoder.decoder_block3.dec_att.aspp_deforms.0.bn.num_batches_tracked", "decoder.decoder_block3.dec_att.aspp_deforms.1.bn.weight", "decoder.decoder_block3.dec_att.aspp_deforms.1.bn.bias", "decoder.decoder_block3.dec_att.aspp_deforms.1.bn.running_mean", "decoder.decoder_block3.dec_att.aspp_deforms.1.bn.running_var", "decoder.decoder_block3.dec_att.aspp_deforms.1.bn.num_batches_tracked", "decoder.decoder_block3.dec_att.aspp_deforms.2.bn.weight", "decoder.decoder_block3.dec_att.aspp_deforms.2.bn.bias", "decoder.decoder_block3.dec_att.aspp_deforms.2.bn.running_mean", "decoder.decoder_block3.dec_att.aspp_deforms.2.bn.running_var", "decoder.decoder_block3.dec_att.aspp_deforms.2.bn.num_batches_tracked", "decoder.decoder_block3.dec_att.global_avg_pool.2.weight", "decoder.decoder_block3.dec_att.global_avg_pool.2.bias", "decoder.decoder_block3.dec_att.global_avg_pool.2.running_mean", "decoder.decoder_block3.dec_att.global_avg_pool.2.running_var", "decoder.decoder_block3.dec_att.global_avg_pool.2.num_batches_tracked", "decoder.decoder_block3.dec_att.bn1.weight", "decoder.decoder_block3.dec_att.bn1.bias", "decoder.decoder_block3.dec_att.bn1.running_mean", "decoder.decoder_block3.dec_att.bn1.running_var", "decoder.decoder_block3.dec_att.bn1.num_batches_tracked", "decoder.decoder_block3.bn_in.weight", "decoder.decoder_block3.bn_in.bias", "decoder.decoder_block3.bn_in.running_mean", "decoder.decoder_block3.bn_in.running_var", "decoder.decoder_block3.bn_in.num_batches_tracked", "decoder.decoder_block3.bn_out.weight", "decoder.decoder_block3.bn_out.bias", "decoder.decoder_block3.bn_out.running_mean", "decoder.decoder_block3.bn_out.running_var", "decoder.decoder_block3.bn_out.num_batches_tracked", "decoder.decoder_block2.dec_att.aspp1.bn.weight", "decoder.decoder_block2.dec_att.aspp1.bn.bias", "decoder.decoder_block2.dec_att.aspp1.bn.running_mean", "decoder.decoder_block2.dec_att.aspp1.bn.running_var", "decoder.decoder_block2.dec_att.aspp1.bn.num_batches_tracked", "decoder.decoder_block2.dec_att.aspp_deforms.0.bn.weight", "decoder.decoder_block2.dec_att.aspp_deforms.0.bn.bias", "decoder.decoder_block2.dec_att.aspp_deforms.0.bn.running_mean", "decoder.decoder_block2.dec_att.aspp_deforms.0.bn.running_var", "decoder.decoder_block2.dec_att.aspp_deforms.0.bn.num_batches_tracked", "decoder.decoder_block2.dec_att.aspp_deforms.1.bn.weight", "decoder.decoder_block2.dec_att.aspp_deforms.1.bn.bias", "decoder.decoder_block2.dec_att.aspp_deforms.1.bn.running_mean", "decoder.decoder_block2.dec_att.aspp_deforms.1.bn.running_var", "decoder.decoder_block2.dec_att.aspp_deforms.1.bn.num_batches_tracked", "decoder.decoder_block2.dec_att.aspp_deforms.2.bn.weight", "decoder.decoder_block2.dec_att.aspp_deforms.2.bn.bias", "decoder.decoder_block2.dec_att.aspp_deforms.2.bn.running_mean", "decoder.decoder_block2.dec_att.aspp_deforms.2.bn.running_var", "decoder.decoder_block2.dec_att.aspp_deforms.2.bn.num_batches_tracked", "decoder.decoder_block2.dec_att.global_avg_pool.2.weight", "decoder.decoder_block2.dec_att.global_avg_pool.2.bias", "decoder.decoder_block2.dec_att.global_avg_pool.2.running_mean", "decoder.decoder_block2.dec_att.global_avg_pool.2.running_var", "decoder.decoder_block2.dec_att.global_avg_pool.2.num_batches_tracked", "decoder.decoder_block2.dec_att.bn1.weight", "decoder.decoder_block2.dec_att.bn1.bias", "decoder.decoder_block2.dec_att.bn1.running_mean", "decoder.decoder_block2.dec_att.bn1.running_var", "decoder.decoder_block2.dec_att.bn1.num_batches_tracked", "decoder.decoder_block2.bn_in.weight", "decoder.decoder_block2.bn_in.bias", "decoder.decoder_block2.bn_in.running_mean", "decoder.decoder_block2.bn_in.running_var", "decoder.decoder_block2.bn_in.num_batches_tracked", "decoder.decoder_block2.bn_out.weight", "decoder.decoder_block2.bn_out.bias", "decoder.decoder_block2.bn_out.running_mean", "decoder.decoder_block2.bn_out.running_var", "decoder.decoder_block2.bn_out.num_batches_tracked", "decoder.decoder_block1.dec_att.aspp1.bn.weight", "decoder.decoder_block1.dec_att.aspp1.bn.bias", "decoder.decoder_block1.dec_att.aspp1.bn.running_mean", "decoder.decoder_block1.dec_att.aspp1.bn.running_var", "decoder.decoder_block1.dec_att.aspp1.bn.num_batches_tracked", "decoder.decoder_block1.dec_att.aspp_deforms.0.bn.weight", "decoder.decoder_block1.dec_att.aspp_deforms.0.bn.bias", "decoder.decoder_block1.dec_att.aspp_deforms.0.bn.running_mean", "decoder.decoder_block1.dec_att.aspp_deforms.0.bn.running_var", "decoder.decoder_block1.dec_att.aspp_deforms.0.bn.num_batches_tracked", "decoder.decoder_block1.dec_att.aspp_deforms.1.bn.weight", "decoder.decoder_block1.dec_att.aspp_deforms.1.bn.bias", "decoder.decoder_block1.dec_att.aspp_deforms.1.bn.running_mean", "decoder.decoder_block1.dec_att.aspp_deforms.1.bn.running_var", "decoder.decoder_block1.dec_att.aspp_deforms.1.bn.num_batches_tracked", "decoder.decoder_block1.dec_att.aspp_deforms.2.bn.weight", "decoder.decoder_block1.dec_att.aspp_deforms.2.bn.bias", "decoder.decoder_block1.dec_att.aspp_deforms.2.bn.running_mean", "decoder.decoder_block1.dec_att.aspp_deforms.2.bn.running_var", "decoder.decoder_block1.dec_att.aspp_deforms.2.bn.num_batches_tracked", "decoder.decoder_block1.dec_att.global_avg_pool.2.weight", "decoder.decoder_block1.dec_att.global_avg_pool.2.bias", "decoder.decoder_block1.dec_att.global_avg_pool.2.running_mean", "decoder.decoder_block1.dec_att.global_avg_pool.2.running_var", "decoder.decoder_block1.dec_att.global_avg_pool.2.num_batches_tracked", "decoder.decoder_block1.dec_att.bn1.weight", "decoder.decoder_block1.dec_att.bn1.bias", "decoder.decoder_block1.dec_att.bn1.running_mean", "decoder.decoder_block1.dec_att.bn1.running_var", "decoder.decoder_block1.dec_att.bn1.num_batches_tracked", "decoder.decoder_block1.bn_in.weight", "decoder.decoder_block1.bn_in.bias", "decoder.decoder_block1.bn_in.running_mean", "decoder.decoder_block1.bn_in.running_var", "decoder.decoder_block1.bn_in.num_batches_tracked", "decoder.decoder_block1.bn_out.weight", "decoder.decoder_block1.bn_out.bias", "decoder.decoder_block1.bn_out.running_mean", "decoder.decoder_block1.bn_out.running_var", "decoder.decoder_block1.bn_out.num_batches_tracked", "decoder.gdt_convs_4.1.weight", "decoder.gdt_convs_4.1.bias", "decoder.gdt_convs_4.1.running_mean", "decoder.gdt_convs_4.1.running_var", "decoder.gdt_convs_4.1.num_batches_tracked", "decoder.gdt_convs_3.1.weight", "decoder.gdt_convs_3.1.bias", "decoder.gdt_convs_3.1.running_mean", "decoder.gdt_convs_3.1.running_var", "decoder.gdt_convs_3.1.num_batches_tracked", "decoder.gdt_convs_2.1.weight", "decoder.gdt_convs_2.1.bias", "decoder.gdt_convs_2.1.running_mean", "decoder.gdt_convs_2.1.running_var", "decoder.gdt_convs_2.1.num_batches_tracked". 
```

## Questions
1. Is there a compatibility issue between the pre-trained model and the current architecture?
2. Are there any specific steps I should take to resolve this state dictionary mismatch?
3. Could you provide guidance on how to properly resume training from the pre-trained model with my custom dataset?

## Additional Information
I'm happy to provide any further details or run additional diagnostics as needed. Thank you in advance for your assistance.

**Comment by ZhengPeng7** [comment]
Hi, @kiveboxops; thanks for your detailed descriptions.
It's an easy problem -- I used `batch size = 4` to obtain existing weights. Therefore, the `batch normalization` (BN) is open there. However, if you set the batch size as 1, it cannot have the BN, which causes the incompatibility you provided above. So, you can either use `BiReNet_lite`, which is also for general use but with `swin_v1_tiny` as the backbone, or use GPUs with more than 36 GB (batch size can be set to 2 when resolution is 1024x1024), as I said in README.

**Comment by ZhengPeng7** [comment]
BTW, you can also skip loading the BN values of the provided weights. But I'm unsure about the performance of this way to use it.
