### ISSUE TITLE
使用DIS5K数据集单GPU训练报错

### ISSUE THREAD

**Issue by huchunjun425** [ZhengPeng7/BiRefNet#103]
您好，请问一下，我使用单GPU训练github下载得指定代码，使用“./train_test.sh train 1 1”命令尝试训练代码时，报错如下：Single-GPU mode received...
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    from models.birefnet import BiRefNet
  File "/mnt/data/code/semanticSegmentation/huChunJun/BiRefNet/models/birefnet.py", line 9, in <module>
    from models.backbones.build_backbone import build_backbone
  File "/mnt/data/code/semanticSegmentation/huChunJun/BiRefNet/models/backbones/build_backbone.py", line 4, in <module>
    from torchvision.models import vgg16, vgg16_bn, VGG16_Weights, VGG16_BN_Weights, resnet50, ResNet50_Weights
ImportError: cannot import name 'VGG16_Weights' from 'torchvision.models' (/root/anaconda3/envs/hcjcnn/lib/python3.7/site-packages/torchvision/models/__init__.py)
请问一下这个是由于什么原因导致得？我按照要求进入build_backbone.py文件里面，发现from torchvision.models import vVGG16_Weights, VGG16_BN_Weights, ResNet50_Weights三个模块无法追踪。

**Comment by ZhengPeng7** [comment]
torch版本太旧了.

**Comment by huchunjun425** [comment]
谢谢您的回复！
---- 回复的原邮件 ----
发件人Peng ***@***.***>发送日期2024年10月10日 20:08 ***@***.***> ***@***.***>,
***@***.***>主题Re: [ZhengPeng7/BiRefNet] 使用DIS5K数据集单GPU训练报错 (Issue #103)
torch版本太旧了.

**Comment by huchunjun425** [comment]
您好，郑老师，由于我个人不是计算机专业的学生，我看read.me 里面有关训练验证的细节信息不是很详细，所以个人不太懂！麻烦老师解答一下，训练完成之后，请问一下我该如何基于训练完的权重进行验证呢？我使用“eval_existingOnes.py”验证的时候，总是报错  out of list.......。哪个地方需要我设置传入的权重参数，我个人找了一圈没有找到，我的理解不太够！
        
    
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年10月11日 09:33
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              回复：[ZhengPeng7/BiRefNet] 使用DIS5K数据集单GPU训练报错 (Issue #103)
        
      
    
  
谢谢您的回复！---- 回复的原邮件 ----发件人Peng ***@***.***>发送日期2024年10月10日 20:08 ***@***.***> ***@***.***>***@***.***>主题Re: [ZhengPeng7/BiRefNet] 使用DIS5K数据集单GPU训练报错 (Issue #103)
torch版本太旧了.

**Comment by ZhengPeng7** [comment]
客气了, 我也还是学生. 你就用DIS5K作为例子, 什么都不改, 直接跑一下整个项目看看流程? 可以把每个子数据集里就留20张图来加速这个过程.

**Comment by huchunjun425** [comment]
***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Peng ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年10月10日 20:08
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ZhengPeng7/BiRefNet] 使用DIS5K数据集单GPU训练报错 (Issue #103)
        
      
    
  

torch版本太旧了.
