### ISSUE TITLE
KeyError: 'HOME'

### ISSUE THREAD

**Issue by gg22mm** [ZhengPeng7/BiRefNet#54]
E:\ProgramData\miniconda3\envs\mygpt39\lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
E:\ProgramData\miniconda3\envs\mygpt39\lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "E:\web_soft\phpsys2\www\u_server\u3\test\resnet\tool\图像接口\去背景.py", line 36, in <module>
    birefnet = AutoModelForImageSegmentation.from_pretrained('models/ZhengPeng7/BiRefNet', trust_remote_code=True)
  File "E:\ProgramData\miniconda3\envs\mygpt39\lib\site-packages\transformers\models\auto\auto_factory.py", line 553, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "E:\ProgramData\miniconda3\envs\mygpt39\lib\site-packages\transformers\dynamic_module_utils.py", line 500, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "E:\ProgramData\miniconda3\envs\mygpt39\lib\site-packages\transformers\dynamic_module_utils.py", line 200, in get_class_in_module
    module = importlib.import_module(module_path)
  File "E:\ProgramData\miniconda3\envs\mygpt39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\BiRefNet\birefnet.py", line 1392, in <module>
    config = Config()
  File "C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\BiRefNet\birefnet.py", line 10, in __init__
    self.sys_home_dir = os.environ['HOME']     # Make up your file system as: SYS_HOME_DIR/codes/dis/BiRefNet, SYS_HOME_DIR/datasets/dis/xx, SYS_HOME_DIR/weights/xx
  File "E:\ProgramData\miniconda3\envs\mygpt39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'

**Comment by ZhengPeng7** [comment]
Hi, all the scripts are mainly designed for Linux.
Therefore, you need to change the `sys_home_dir` to the root dir of projects in your system.
You can refer to [the previous issue](https://github.com/ZhengPeng7/BiRefNet/issues/43#issuecomment-2247198180) for a detailed file structure.
