### ISSUE TITLE
使用optimum-cli导出为ONNX报错

### ISSUE THREAD

**Issue by czxichen** [ZhengPeng7/BiRefNet#67]
optimum-cli export onnx  --model ZhengPeng7/BiRefNet --trust-remote-code --framework pt new_onnx
/usr/local/anaconda3/envs/yolov10/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/yolov10/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/yolov10/lib/python3.9/site-packages/optimum/commands/optimum_cli.py", line 208, in main
    service.run()
  File "/usr/local/anaconda3/envs/yolov10/lib/python3.9/site-packages/optimum/commands/export/onnx.py", line 265, in run
    main_export(
  File "/usr/local/anaconda3/envs/yolov10/lib/python3.9/site-packages/optimum/exporters/onnx/__main__.py", line 293, in main_export
    model = TasksManager.get_model_from_task(
  File "/usr/local/anaconda3/envs/yolov10/lib/python3.9/site-packages/optimum/exporters/tasks.py", line 1945, in get_model_from_task
    model_class = TasksManager.get_model_class_for_task(
  File "/usr/local/anaconda3/envs/yolov10/lib/python3.9/site-packages/optimum/exporters/tasks.py", line 1380, in get_model_class_for_task
    raise ValueError(
ValueError: Unrecognized configuration classes ('AutoModelForImageSegmentation', 'AutoModelForSemanticSegmentation') do not match with the model type SegformerForSemanticSegmentation and task image-segmentation.

这个应该用什么方式转ONNX？

**Comment by ZhengPeng7** [comment]
You can check the ONNX conversion part in the model zoo section. There is a shared colab for it.

**Comment by czxichen** [comment]
感谢
