### ISSUE TITLE
Train with my custom large dataset

### ISSUE THREAD

**Issue by yaju1234** [ZhengPeng7/BiRefNet#98]
I have a large dataset of 300K images with different objects,car,human, animals, etc. Should I need to train from scratch or I can do transfer learning from your general pre-trained model?

**Comment by ZhengPeng7** [comment]
300K is huge enough to set up the training from scratch. I recommend you do that to achieve better performance in your cases.
But you can also first do an inference on my model to take a look at how the performance is, to provide a comparison with the results you obtain on your custom data.

**Comment by yaju1234** [comment]
Thank you for your valuable response. If I were to train the model from scratch, how many epochs would I need, and how long would the training take if I use an A100 80 GPU?

**Comment by ZhengPeng7** [comment]
Hi, you can refer to the [training log](https://drive.google.com/file/d/1jKf7z0_gWB83cCaqJsVSoh6W1epGYjoZ/view?usp=drive_link) of BiRefNet on DIS5K with 8 A100-80G GPUs, where the training set has `3,000` images.

Since your training set is so large and you have only one GPU, I suggest you save the checkpoints from the first epoch to check the performance of each of them. You can keep it training and copy the checkpoint of epoch-3 to another place to conduct inference and evaluation, which should already have some decent results.

**Comment by yaju1234** [comment]
When training with A100-40G,  what should be the batch size for image size 1024*1024? What is the expected time to complete a epoch of 100K dataset?

**Comment by ZhengPeng7** [comment]
You can set the batch size to 2. I don't have those training log files now, which record the timeline. You can start hundreds of iterations to estimate the time for one complete epoch.

**Comment by yaju1234** [comment]
Thanks . 
I have started training with 5k dataset using A100-40G. After running the train.sh the application stuck for a white and show the bellow error log

**Traceback (most recent call last):
  File "/content/drive/MyDrive/BiRefNet/train.py", line 342, in <module>
    main()
  File "/content/drive/MyDrive/BiRefNet/train.py", line 328, in main
    train_loss = trainer.train_epoch(epoch)
  File "/content/drive/MyDrive/BiRefNet/train.py", line 302, in train_epoch
    self._train_batch(batch)
  File "/content/drive/MyDrive/BiRefNet/train.py", line 238, in _train_batch
    scaled_preds, class_preds_lst = self.model(inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/BiRefNet/models/birefnet.py", line 114, in forward
    scaled_preds, class_preds = self.forward_ori(x)
  File "/content/drive/MyDrive/BiRefNet/models/birefnet.py", line 103, in forward_ori
    (x1, x2, x3, x4), class_preds = self.forward_enc(x)
  File "/content/drive/MyDrive/BiRefNet/models/birefnet.py", line 71, in forward_enc
    x1, x2, x3, x4 = self.bb(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/BiRefNet/models/backbones/swin_v1.py", line 597, in forward
    x_out, H, W, x, Wh, Ww = layer(x, Wh, Ww)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/BiRefNet/models/backbones/swin_v1.py", line 379, in forward
    Hp = int(np.ceil(H / self.window_size)) * self.window_size
  File "/content/drive/MyDrive/BiRefNet/models/backbones/swin_v1.py", line 380, in torch_dynamo_resume_in_forward_at_379
    Wp = int(np.ceil(W / self.window_size)) * self.window_size
  File "/content/drive/MyDrive/BiRefNet/models/backbones/swin_v1.py", line 400, in torch_dynamo_resume_in_forward_at_380
    blk.H, blk.W = H, W
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 921, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 786, in _convert_frame
    result = inner_convert(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 676, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 535, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/bytecode_transformation.py", line 1036, in transform_code_object
    transformations(instructions, code_options)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 500, in transform
    tracer.run()
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2149, in run
    super().run()
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 810, in run
    and self.step()
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2268, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1001, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1178, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1251, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1232, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1731, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1330, in compile_fx
    return aot_autograd(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/backends/common.py", line 58, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 903, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 628, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 443, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 648, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 352, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(fw_module, adjusted_flat_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1257, in fw_compiler_base
    return inner_compile(
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 438, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 698, in fx_codegen_and_compile
    graph.run(*example_inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/graph.py", line 612, in run
    return super().run(*args)
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/interpreter.py", line 145, in run
    self.env[node] = self.run_node(node)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/graph.py", line 957, in run_node
    result = super().run_node(n)
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/interpreter.py", line 202, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/graph.py", line 819, in call_function
    raise LoweringException(e, target, args, kwargs).with_traceback(
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/graph.py", line 816, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/lowering.py", line 296, in wrapped
    out = decomp_fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/lowering.py", line 3103, in index
    return index_impl(x, indices, check=True)
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/lowering.py", line 3065, in index_impl
    indices, tensor_indices = check_and_broadcast_indices(indices, x.get_device())
  File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/lowering.py", line 2968, in check_and_broadcast_indices
    assert all(
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: AssertionError: indices must be int64, byte or bool. Got [torch.float32]
  target: aten.index.Tensor
  args[0]: TensorBox(StorageBox(
    Pointwise(
      'cuda',
      torch.float32,
      def inner_fn(index):
          _, i1, i2, i3 = index
          tmp0 = ops.index_expr(i1, torch.int64)
          tmp1 = ops.index_expr(s4, torch.int64)
          tmp2 = tmp0 < tmp1
          tmp3 = ops.index_expr(i2, torch.int64)
          tmp4 = ops.index_expr(s5, torch.int64)
          tmp5 = tmp3 < tmp4
          tmp6 = tmp2 & tmp5
          tmp7 = ops.load(buf36, i3 + 384 * i2 + 384 * s5 * i1)
          tmp8 = ops.load(primals_15, i3)
          tmp9 = tmp7 * tmp8
          tmp10 = ops.load(primals_16, i3)
          tmp11 = tmp9 + tmp10
          tmp12 = ops.masked(tmp6, tmp11, 0.0)
          return tmp12
      ,
      ranges=[1, s4 + Mod(12 - Mod(s4, 12), 12), s5 + Mod(12 - Mod(s5, 12), 12), 384],
      origin_node=constant_pad_nd_1,
      origins={constant_pad_nd_1}
    )
  ))
  args[1]: [None, TensorBox(StorageBox(
    Pointwise(
      'cuda',
      torch.float32,
      def inner_fn(index):
          i0 = index
          tmp0 = ops.index_expr(i0, dtype=torch.int64)
          tmp1 = ops.to_dtype(tmp0, torch.float32, src_dtype=torch.int64)
          tmp2 = ops.index_expr(Mod(s4 + Mod(12 - Mod(s4, 12), 12) + 6, s4 + Mod(12 - Mod(s4, 12), 12)), torch.float32)
          tmp3 = tmp1 + tmp2
          tmp4 = ops.index_expr(s4 + Mod(12 - Mod(s4, 12), 12), torch.float32)
          tmp5 = ops.fmod(tmp3, tmp4)
          return tmp5
      ,
      ranges=[s4 + Mod(12 - Mod(s4, 12), 12)],
      origin_node=fmod,
      origins={iota, fmod, add_11}
    )
  ))]

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

Training finished at Tue Oct 29 01:35:59 PM UTC 2024** 

Can you please help me on this issue.

**Comment by ZhengPeng7** [comment]
Are you sure you're using exactly the same requirements as given in my repo? If so, change the `compile` in `config.py` to `False`.

**Comment by yaju1234** [comment]
I am using "
Name: torch
Version: 2.5.0+cu121

Name: torchvision
Version: 0.20.0+cu121

**Comment by yaju1234** [comment]
**Subject**: Performance Degradation in BiRefNet Training Across Epochs

**Description**: I am experiencing performance degradation while training BiRefNet for salient object detection on a diverse dataset of 300K images, including humans, animals, objects, cars, and more. Here are the specific details:

**Dataset and Setup**:

- The dataset includes various categories such as humans, animals, cars, and objects.


**Issue Observed**:

- Some test images perform well in one epoch but show degraded results in subsequent epochs.
- Inconsistent performance is observed even for identical test images across epochs.
- The model's output appears to fluctuate, with certain images performing well in early epochs but poorly later.

**Questions**:

- Are there recommended configurations for training BiRefNet on large and diverse datasets?
- Any debugging strategies or optimization techniques to stabilize training across epochs?

I would appreciate your insights or suggestions on how to resolve this issue. Thank you for your work on BiRefNet!

**Comment by ZhengPeng7** [comment]
If the training is very unstable, I suggest you decrease the learning rate.
Besides, if you directly use my project, you should have all the evaluation scores of every epoch (if you set the step to 1). You can use those instead of some single samples to have a more overall comparison.
Also, you can take a look at the [finetune_last_epochs](https://github.com/ZhengPeng7/BiRefNet/blob/4161086bb31b44f13390923e5ecfad333006f3f6/train.py#L209) in `train.py` if it's also good to decrease some loss weights in the last epochs of training to avoid large pertubations.

**Comment by yaju1234** [comment]
Thank you for the suggestion regarding logging evaluation scores for every epoch by setting the step to 1. I have identified the section in the script where step is set for different tasks, such as:
```
case "${task}" in
    'DIS5K') epochs=500 && val_last=50 && step=5 ;;
    'COD') epochs=150 && val_last=50 && step=5 ;;
    ...
esac
```
 plan to update step=5 to step=1 for the relevant tasks to log evaluation scores for every epoch. Could you confirm if this is the correct approach, or is there another location in the code where I should make this change?

Additionally, I expected evaluation metrics to be logged in the log.txt file, but I could not find any specific code in the script that writes evaluation metrics to the log. Could you clarify where and how the evaluation metrics are logged, or if there’s any setup required to enable logging?

Thank you for your guidance!

**Comment by ZhengPeng7** [comment]
Yeah, that's correct.
About the metric scores, I split the training and test+eval. You can check `train_test.sh` to see the details.
Once the whole program is finished, you will see the scores printed into tables in some .txt files under the `e_results` folder.

**Comment by yaju1234** [comment]
I have been training it using my custom dataset, which contains 50,000 images of humans (both single and multiple individuals in various scenarios). After 40 epochs, the loss is around 5.5, and the model is performing well. However, the output quality is still not meeting my expectations.

I would appreciate your advice on the following:

-     Should I continue training for more epochs, or could this lead to overfitting?

-     Is there a specific loss threshold or any other metric I should aim for before stopping the training?

-     Are there additional steps you recommend to enhance the quality further (e.g., fine-tuning, augmentations, or parameter adjustments)?

Thank you in advance for your guidance.

**Comment by ZhengPeng7** [comment]
I'm not sure about your training datasets. But if you have 50k images, you should not do the fine-tuning. Training from scratch is a better choice.
Then, you may adapt the weights of loss to see the difference. You can add some validation steps during training to see the performance, but I still prefer to do the training and test+eval one by one.
What's more, if the model you obtained is even worse than the existing weights I provided before, I suggest you take a deep look at your custom data.
